name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    name: Publish competitive-lib
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Bundle competitive-lib
        run: |
          pip3 install online-judge-verify-helper
          oj-bundle template.cpp > source.cpp
      - name: Upload competitive-lib
        uses: actions/upload-artifact@v2
        with:
          name: source.cpp
          path: ./source.cpp
